name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline:lattest
      - name: Delete Old Docker image
        run: sudo docker rm -f tagname || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name tagname ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline
